env:
  DOCKER_IMAGE_NAME: polystack

name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      run_deploy:
        description: "Deploy Image?"
        required: true
        type: boolean

jobs:

  job-1:
    name: Build and Push Docker Image
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest

  job-2:
    name: Deploy to Local Docker Host
    runs-on: self-hosted
    needs: 
      - job-1

    if: ${{ github.event.inputs.run_deploy == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Pull latest Docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Context  
        run: |
          docker context create ${{ env.DOCKER_IMAGE_NAME }}_context --docker host=${{ secrets.DOCKER_HOST_IP }}
          docker context use ${{ env.DOCKER_IMAGE_NAME }}_context

      - name: Stop and remove existing container
        run: |
          docker stop ${{ env.DOCKER_IMAGE_NAME }} || true
          docker rm ${{ env.DOCKER_IMAGE_NAME }} || true

      - name: Run new container
        run: |
          docker run -d --name ${{ env.DOCKER_IMAGE_NAME }} -p 5000:5000 ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
